features:
  enable_cover_image_download: true
  enable_formatted_message_search: true
output:
  image_folder: /app/sharedFolder/ehentai/tempImages
  jpeg_quality: 85
  max_filename_length: 200
  max_pages_per_pdf: 200
  pdf_folder: /app/sharedFolder/ehentai/pdf
  search_cache_folder: /app/sharedFolder/ehentai/searchCache
platform:
  api_token: ''
  http_host: 192.168.5.2
  http_port: 13000
  type: napcat
request:
  concurrency: 10
  cookies:
    igneous: a5noy97v1mqkaa1m6
    ipb_member_id: '8973652'
    ipb_pass_hash: 37e5f2975fcc2c46e5f211ac94d55a0f
  headers:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/134.0.0.0 Safari/537.36
  max_retries: 3
  proxies: http://192.168.5.2:17893
  proxy:
    auth: null
    url: http://192.168.5.2:17893
  timeout: 5
  website: exhentai
